# Site settings
title: DDDR
email: dejan@dddr.ch
description: > # this means to ignore newlines until "baseurl:"
  Digital transformation is not easy. We work with you to make sense of the opportunities and challenges posed by the new technology.
  We also make sure that you don't spend a fortune on unnecessary new gadgets that the industry is promoting.
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
